# -*- coding: utf-8 -*-
"""HermesCifar10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OUvQ67g_1CSN-cB20VKgQhxmkNRA5hJh
"""



import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from os import listdir
from tensorflow.keras.preprocessing import sequence
import tensorflow as tfs
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.layers import LSTM

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import ModelCheckpoint

from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Flatten, Conv2D, MaxPooling2D,LeakyReLU,MaxPool2D,GlobalAveragePooling2D
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2, random

height=32
width=32
depth=3

inputShape = (height, width, depth)

# Prepare the train and test dataset.
from tensorflow import keras
# batch_size = 64
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
print(x_train.shape)
# Normalize data
x_train = x_train.astype("float32") / 255.0
x_train = np.reshape(x_train, (-1, 32, 32, 3))

x_test = x_test.astype("float32") / 255.0
x_test = np.reshape(x_test, (-1, 32, 32, 3))
y_train=np.reshape(y_train,(-1))
y_test=np.reshape(y_test,(-1))

from  keras.utils import np_utils
# y_train = np_utils.to_categorical(y_train)
# y_test= np_utils.to_categorical(y_test)
print(y_train[0])
print(y_train.shape,y_test.shape)
print(x_train.shape)
print(y_train[0],x_train[0])

from sklearn.utils import shuffle
x_train, y_train= shuffle(x_train, y_train, random_state=42)
X=[]
Y=[]
j=0
for i in range(20):
  X.append(x_train[j:j+2500])
  Y.append(y_train[j:j+2500])
  j+=2500

X=np.array(X)
Y=np.array(Y)
print(X.shape,Y.shape)

from tensorflow.keras.layers import BatchNormalization
class MODEL:
    @staticmethod
    def build():

        #resnet
        model = Sequential()
        model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same', input_shape=(32, 32, 3)))

        model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(BatchNormalization())
        model.add(MaxPool2D((2, 2)))
        model.add(Dropout(0.5))
        model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(BatchNormalization())
        model.add(MaxPool2D((2, 2)))
        model.add(Dropout(0.5))
        model.add(Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(BatchNormalization())
        model.add(MaxPool2D((2, 2)))
        model.add(Dropout(0.5))
        model.add(Conv2D(512, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(512, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(512, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(Conv2D(512, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        # model.add(BatchNormalization())
        model.add(GlobalAveragePooling2D())
        model.add(Flatten())
        # model.add(Dense(128, activation='relu', kernel_initializer='he_uniform'))
        model.add(Dense(10,activation='softmax'))
        return model

from sklearn.metrics import accuracy_score
def test_model(X_test, Y_test,  model, comm_round):
    # cce = tf.keras.losses.SparseCategoricalCrossentropy()
    # #logits = model.predict(X_test, batch_size=100)
    # logits = model.predict(X_test)
    # loss = cce(Y_test, logits)
    # acc = accuracy_score(tf.argmax(logits, axis=1), tf.argmax(Y_test, axis=1))
    # print('comm_round: {} | global_acc: {:.3%} | global_loss: {}'.format(comm_round, acc, loss))
    model.compile(  optimizer=keras.optimizers.Adam(),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)
    # loss,acc=model.evaluate(x_test,y_test)
    acc,loss=model.evaluate(x_test,y_test)
    return acc, loss
def scale_model_weights(weight, scalar):
    '''function for scaling a models weights'''
    weight_final = []
    steps = len(weight)
    for i in range(steps):
        weight_final.append(scalar * weight[i])
    return weight_final

def sum_scaled_weights(scaled_weight_list,global_weights):
    '''Return the sum of the listed scaled weights. The is equivalent to scaled avg of the weights'''
    avg_grad = list()
    lcounter=0
    #get the average grad accross all client gradients
    for grad_list_tuple in zip(*scaled_weight_list):
        tmplist=list()
        # print("GLT",np.array(grad_list_tuple).shape)
        for i in range(len(grad_list_tuple)):
          if(np.count_nonzero(grad_list_tuple[i]==0.0)<=5):
            tmplist.append(grad_list_tuple[i])
        # print("tmplist",len(tmplist))
        # scale_model_weights(tmplist,len(tmplist))
        layer_mean = tf.math.reduce_sum(tmplist, axis=0)/len(tmplist)
        # print("shape",layer_mean.shape)
        if(len(tmplist)==0):
          layer_mean=global_weights[lcounter].copy()
          print("global shape",global_weights[lcounter].shape)
          print("newshape",layer_mean.shape)
        avg_grad.append(layer_mean)
        lcounter=lcounter+1
      
    return avg_grad

from tensorflow import keras
import math

global1= MODEL()
global_model = global1.build()
comms_round = 50
# print(trainy[2].shape)
f= open("HermesMNIST.txt", "a+") 
f.close()
f1= open("HermesMNISTGlobal.txt", "a+") 
f1.close()

totalparticipants=20
epoch=np.random.randint(10,21,totalparticipants)
print(epoch)
from tensorflow.keras import backend as K
for comm_round in range(200):
  if(comm_round==0 and comm_round%10==0):
   for var in range(int(len(X)/2)):
    i,j=random.randrange(0,len(X)),random.randrange(0,len(X))
    X[i],X[j]=X[j],X[i]
    Y[i],Y[j]=Y[j],Y[i]
    print("i",i,"j",j) 

  f= open("HermesMNIST.txt", "a+") 
  f1= open("HermesMNISTGlobal.txt", "a+") 
  global_weights = global_model.get_weights()
  scaled_local_weight_list = list()
  index=list({0,1,2,3,4})
  #random.shuffle(index)
  # print(index)
  f.write("\nCommunication Round:%d \n" %comm_round)
  print("Communication Round:",comm_round,"\n")

  for ind in range(20):
    print("CLIENT NO: ",ind)
    f.write("Client No: %d\n" %ind)
    local = MODEL()
    local_model=local.build()
    
    local_model.compile(optimizer=keras.optimizers.Adam(),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
    
)
    local_model.set_weights(global_weights)
    #trainy[ind]=np.array(trainy[ind]).reshape(-1,1)
    local_model.fit(X[ind],Y[ind], epochs=epoch[ind])#,batch_size=1)#,validation_data=(x_test,y_test))
    # print("Accuracy: ",history.history["accuracy"][4])
    # local_model.evaluate(x_test, y_test)
    # testsampley=np.array([Y[ind][0]])
    # # print(testsampley)
    # testsamplex=np.array([X[ind][0]])
    # # print(testsamplex)
    # lloss,lacc=test_model(testsamplex,testsampley, local_model, comm_round)
    # print("LOSS",lloss,"ACC",lacc)


    local_loss, local_acc = test_model(x_test,y_test, local_model, comm_round)
    # if(comm_round==19):
    f.write("Communication Round: %d Local Model ACCURACY: %f LOSS: %f \n" %(comm_round ,local_acc ,local_loss))
    # scaling_factor=1.0/20 #1/no.ofclients
    # scaled_weights = scale_model_weights(local_model.get_weights(), scaling_factor)
    ogwt=local_model.get_weights()
    sendwt=ogwt.copy()
    
    #if masking based on max min uncomment below
    # mxmean=10
    # mxmeanind=-1
    # layercounter=0
    # for lyr in range(len(local_model.layers)):
    #    if(np.array(local_model.layers[lyr].get_weights()).shape[0]>=1):
          

    #       wt,bs=local_model.layers[lyr].get_weights()
    #       # print(wt.shape,bs.shape)
    #       # print(np.mean(wt),np.min(wt))
    #       if(np.min(wt)<mxmean):
    #         mxmean=np.min(wt)
    #         mxmeanind=layercounter
    #       layercounter=layercounter+1

    #       # print(np.max(wt),np.min(wt))
    # # print(mxmeanind)
    # # print("Sendwtmax",np.max(sendwt[2*mxmeanind]))
    # sendwt[2*mxmeanind][:]=0
    # sendwt[2*mxmeanind+1][:]=0


    #random masking
    randlayer=random.randrange(0,6)
    sendwt[2*randlayer][:]=0
    sendwt[2*randlayer+1][:]=0

    scaled_local_weight_list.append(sendwt)

    K.clear_session()

  average_weights = sum_scaled_weights(scaled_local_weight_list,global_weights)
  # np.ndarray.sort(Util)
  # print(Util)
  #global_model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
  global_model.set_weights(average_weights)
  #val_acc,val_loss=global_model.evaluate(x_train,y_train)
  #print(val_loss,val_acc)
  global_loss, global_acc = test_model(x_test,y_test, global_model, comm_round)
  f.write("\nCommunication Round: %d GLOBAL MODEL ACCURACY: %f LOSS: %f \n" %(comm_round ,global_acc ,global_loss))
  f1.write("%f \t %f \n" %(global_acc ,global_loss))
  print("GLOBAL ACC",global_acc,"GLOBAL LOSS",global_loss)

        


  


  f.close()
  f1.close()
